update with new keyword and restructured the code

diff --git a/p2000 b/p2000
--- a/p2000
+++ b/p2000
@@ -11,12 +11,12 @@
 # - curl
 #
 # changelog:
-# v1.0.0	initial version						harald van der laan
-# v1.0.1	added proxy support					harald van der laan
+# v1.0.0	initial version                     harald van der laan
+# v1.0.1	added proxy support                 harald van der laan
 
 if [ -z $(which curl) ]; then
-	echo "[-] requirment curl missing."
-	exit 1
+    echo "[-] requirment curl missing."
+    exit 1
 fi
 
 tmpfile='./p2000.lst'
@@ -32,9 +32,9 @@ norm="\e[0m"
 
 # download p2000 alerts for Gelderland-Midden
 if [ -z ${1} ]; then
-	curl -o ${tmpfile} -sL ${url}${region}
+    curl -o ${tmpfile} -sL ${url}${region}
 else
-	curl --proxy ${1} -o ${tmpfile} -sL ${url}${region}
+    curl --proxy ${1} -o ${tmpfile} -sL ${url}${region}
 fi
 
 # strip all html and realign content
@@ -43,17 +43,19 @@ mv ${tmpfile}.tmp ${tmpfile}
 
 # display alerts with color
 while read line; do
-	if [[ $(egrep 'Lifeliner|LFL' <<< ${line}) ]]; then
-                echo -e "${green}${line}${norm}"
-        elif [[ $(egrep 'GLM_|BRW|Brandweer' <<< ${line}) ]]; then
-                echo -e "${red}${line}${norm}"
-	elif [[ $(egrep "^A[1-2]|Ambu|^B[1-2]|Solo|VWS|CPA|SEH" <<< ${line}) ]]; then 
-		echo -e "${yellow}${line}${norm}"
-	elif [[ $(egrep 'Kust|KNRM' <<< ${line}) ]]; then
-		echo -e "${orange}${line}${norm}"
-	else
-		echo -e "${blue}${line}${norm}"
-	fi
+    if [[ $(egrep 'Lifeliner|LFL|MMT|mmt' <<< ${line}) ]]; then
+        echo -e "${green}${line}${norm}"
+    elif [[ $(egrep 'GLM_|BRW|Brandweer' <<< ${line}) ]]; then
+        echo -e "${red}${line}${norm}"
+    elif [[ $(egrep 'Wachtarts' <<< ${line}) ]]; then
+        echo -e "${blue}${line}${norm}"
+    elif [[ $(egrep "^A[1-2]|Ambu|^B[1-2]|Solo|VWS|CPA|SEH" <<< ${line}) ]]; then 
+        echo -e "${yellow}${line}${norm}"
+    elif [[ $(egrep 'Kust|KNRM' <<< ${line}) ]]; then
+        echo -e "${orange}${line}${norm}"
+    else
+        echo -e "${blue}${line}${norm}"
+    fi
 done < ${tmpfile}
 
 # cleanup
